language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

# We want to use devel devtools to load packages so we can catch package
# installation issues sooner rather than later.
r_github_packages:
  - mlt/csdf

# The git config settings are not setup on travis by default
before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

# Only report coverage for the release version
after_success:
- test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
